{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Errors\n",
    "Errors, also known as Exceptions, are a very common part of Python which you have likely already seen. Errors are\n",
    "raised when Python doesn't know how to handle something or we can throw them manually as well (usually for specific\n",
    "handling of situations). Let's look at a simple mathematical example:\n",
    "\n",
    "```python\n",
    "5 / 0 # we try to divide by 0\n",
    "```\n",
    "\n",
    "```\n",
    "Traceback (most recent call last):\n",
    "  File \"logger.py\", line 1, in <module>\n",
    "    5 / 0\n",
    "ZeroDivisionError: division by zero\n",
    "```\n",
    "\n",
    "As you can see above, when you try to run some code which cannot be handled, an error is thrown. Luckily, there is a\n",
    "readable name which tells us what the issue is `ZeroDivisionError`. Typically, the error names are well named so that you\n",
    "should have an idea as to what could have gone wrong. Similarly, if you decide to create your own error, you should try\n",
    "to give it an easy to understand name so the user is not left wondering what the issue is.\n",
    "\n",
    "## Common Errors \n",
    "\n",
    "### AttributeError\n",
    "The `AttributeError` is raised when we try to access an attribute of a variable that doesn't exist. This can happen when\n",
    "```python\n",
    "from datetime import datetime\n",
    "\n",
    "today = datetime.now()  # creates a datetime object for the current date at the current time\n",
    "today.date              # returns todays date\n",
    "today.not_attribute     # raises AttributeError\n",
    "```\n",
    "\n",
    "### ImportError / ModuleNotFoundError\n",
    "Both the `ImportError` and `ModuleNotFoundError` usually occurs when we try to import something that doesn't exist. There\n",
    "are usually a couple of common reasons this can occur.\n",
    "1. Typo in import\n",
    "2. Package is not installed\n",
    "3. \\[Part of\\] Package location is incorrect\n",
    "\n",
    "```python\n",
    "import jsoon                # raises ModuleNotFoundError\n",
    "                            # this is because jsoon doesn't exist\n",
    "\n",
    "from datetime import lol    # raises ImportError\n",
    "                            # this is because datetime exists but lol doesn't\n",
    "```\n",
    "\n",
    "### IndexError\n",
    "`IndexError` is a frequently encountered error that occurs when we try to access an index of a data structure (list,\n",
    "tuple, etc) that doesn't exist. \n",
    "\n",
    "```python\n",
    "a = [1, 2, 3]\n",
    "\n",
    "a[0]        # returns 1\n",
    "\n",
    "a[4]        # raises IndexError\n",
    "\n",
    "``` \n",
    "\n",
    "### KeyError\n",
    "The `KeyError` is the dictionary equivalent of the IndexError. This happens when we try to access a dictionary with a key\n",
    "that does not exist. This can usually be resolved by using the `get` method for a dictionary.\n",
    "\n",
    "```python\n",
    "a = {\"a\": \"a\", \"b\": \"b\"}\n",
    "a[\"a\"]      # returns a\n",
    "a[\"c\"]      # raises KeyError\n",
    "\n",
    "a.get(\"c\")  # will not raise Error, returns None\n",
    "```\n",
    "\n",
    "### NameError\n",
    "`NameError` is raised when we try to access something that has not yet been defined.\n",
    "```python\n",
    "a = 1\n",
    "\n",
    "a   # returns 1\n",
    "b   # raises NameError\n",
    "``` \n",
    "\n",
    "### SyntaxError\n",
    "`SyntaxError` is a frequent error that can occur when you mistype something. For example, if we mistype `while` in a loop.\n",
    "\n",
    "```python\n",
    "whille True:        # raises SyntaxError\n",
    "    do_something()\n",
    "\n",
    "```\n",
    "\n",
    "### TypeError\n",
    "A `TypeError` is raised when an operation or function is ran on a value that is the wrong type. This can happen when \n",
    "trying to get the length of a variable. This works for a string but not for an int.\n",
    "\n",
    "```python\n",
    "len(\"this string\")  # this returns 11\n",
    "\n",
    "len(5)              # raises TypeError (expecting string)\n",
    "\n",
    "```\n",
    "\n",
    "### Value Error\n",
    "`ValueError` is another common error that is raised when an operation or function is run on an inappropriate value. A\n",
    "common example is when you try to convert a string into an integer but the value does not make sense.\n",
    "\n",
    "```python\n",
    "a = '5'\n",
    "int(a)  # returns 5\n",
    "\n",
    "a = 'five'\n",
    "int(a)  # raises ValueError\n",
    "```\n",
    "\n",
    "### ZeroDivisionError\n",
    "As the name suggests, `ZeroDivisionError` occurs when we try to divide by zero as per our example above.\n",
    "\n",
    "\n",
    "## Handling Errors\n",
    "When errors occur, the program will end and sometimes this can be confusing to the User because they may still expect\n",
    "some functionality to go through. We use a try/except block to try some piece of code and \"catch\" an error if it occurs.\n",
    "Under the except block, we add some logic for what should happen if the error occurs. It is a good habit to specify what\n",
    "error we are expecting instead of using the general `Exception`. This is because you may be expecting a `SyntaxError` but\n",
    "a `ValueError` may occur but you are handling it in a different way. Let's look at an example below which also takes\n",
    "advantage of logging to note the failure. \n",
    "\n",
    "```python\n",
    "import logging\n",
    "\n",
    "logger = logging.getLogger('numbers')\n",
    "logger.setLevel(logging.DEBUG)\n",
    "logger.addHandler(logging.StreamHandler)\n",
    "\n",
    "\n",
    "string_nums = ['1', '2', '3', '$', '5', '6']\n",
    "int_nums = []\n",
    "\n",
    "for number in string_nums:\n",
    "    try:\n",
    "        logger.debug(f'Trying to convert {number}')\n",
    "        int_nums.append(int(number))\n",
    "    except ValueError:\n",
    "         logger.error(f'ERROR: Failed To Convert {number}')\n",
    "``` \n",
    "\n",
    "With the try/catch block, we can also add an `else` and a `finally` block which handles what happens in the case of a\n",
    "non-error and what should be done after everything in the try block has finished.\n",
    "\n",
    "```python\n",
    "try:\n",
    "    file = open('file_name.txt', 'r')\n",
    "    do_something_that_may_cause_error()\n",
    "except ValueError:\n",
    "    handle_value_error()\n",
    "except IndexError:\n",
    "    handle_index_error()\n",
    "else:\n",
    "    no_errors_occured()  # typically is not used\n",
    "finally:\n",
    "    file.close()  # this will run regardless of error or not\n",
    "```\n",
    "\n",
    "The main benefit of the else block is to add code that may be in the try block that shouldn't be there. It is a good habit\n",
    "to ONLY put code in the try block which will trigger the error. Anything else should be put in the else/finally.\n",
    "\n",
    "## Raising Errors\n",
    "When running your code, you may run into errors and handle them. Another thing you may want to do is to raise an error\n",
    "yourself if you foresee an issue. Since you, the developer, have an idea of how the code should work. You may note specific\n",
    "situations where an error can come up. For example, if you code expects a string but receives an int, you can handle throw\n",
    "a TypeError early on.\n",
    "\n",
    "```python\n",
    "\n",
    "user_input = input(\"Please enter a number below 10: \")\n",
    "\n",
    "if int(user_input) >= 10:\n",
    "    raise Exception(\"The Int Must Be Less Than 10\")\n",
    "```\n",
    "\n",
    "\n",
    "## Creating Your Own Exception\n",
    "We will go more into creating objects at a later time but you may find yourself wanting to create an exception. This \n",
    "can be done using the following:\n",
    "\n",
    "```python\n",
    "class ValueTooLargeError(Exception):\n",
    "    pass # we will use the generic Exception to handle everything\n",
    "\n",
    "user_input = input(\"Please enter a number below 10: \")\n",
    "\n",
    "if int(user_input) >= 10:\n",
    "    raise ValueTooLargeError(\"The Int Must Be Less Than 10\")\n",
    "```\n",
    "\n",
    "\\\n",
    "\\\n",
    "\\\n",
    "\\\n",
    "[Up Next: Lesson 5 - Testing](../lesson05-testing/README.md)\n",
    "\\\n",
    "\\\n",
    "\\\n",
    "[Go Back: Lessons 4 - Packages, Input/Output, & Exceptions](README.md)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
